### ISSUE TITLE
Some weird border radiuses on context menu items

### ISSUE THREAD

**Issue by v-briese** [NYRI4/LilyPichu#1]
I found that when right clicking the user settings button and opening its context menu, the second to last item had a weird border and the last item didn't have border radius. Here's some screenshots for better understanding:

![image](https://user-images.githubusercontent.com/35977727/116141081-10f4a480-a68d-11eb-9106-edf6042d3e28.png)

![image](https://user-images.githubusercontent.com/35977727/116141126-1f42c080-a68d-11eb-87fa-2807201d6d97.png)

I would fix it myself and make a pull request but I'm kinda dum hah

**Comment by NYRI4** [comment]
Fixed.
