### ISSUE TITLE
Zoom issues

### ISSUE THREAD

**Issue by ajilidali** [NYRI4/LilyPichu#10]
I keep my discord appearences settings like this : 
![image](https://user-images.githubusercontent.com/40182073/129921722-5e2a7875-a90b-4655-9e66-1bf5c8ccb9aa.png)
but the tags get misplaced on the screen
![image](https://user-images.githubusercontent.com/40182073/129921969-65577f93-17ab-4395-b2e0-29edca0c1454.png)

**Comment by NYRI4** [comment]
The issue isn't on my side, that's Monstrum's donator tags that are not placed correctly, I tried with Black Hole and it had the same problem. You should report this here instead : https://discord.gg/XAru9jqTAN in #bug-reports
