### ISSUE TITLE
theme ig?

### ISSUE THREAD

**Issue by MicroTheBred** [NYRI4/LilyPichu#11]
could you like add the space on the left too cuz it looks kinda off

**Comment by NYRI4** [comment]
This issue needs further informations

**Comment by MicroTheBred** [comment]
![image](https://user-images.githubusercontent.com/79756278/141599967-f125c802-8245-4ee6-80b2-30405a063963.png)
I feel like this edge looks a bit off because it is not consistent with the rest of the edges.

**Comment by Pukimaa** [comment]
What os are you on?

**Comment by MicroTheBred** [comment]
windows 10 21H1

**Comment by NYRI4** [comment]
If you're talking about the container itself, it's part of the theme identity, it can't be changed, here's the original inspiration : https://twitter.com/Melonturtle_/status/1339312498760167430

**Comment by NYRI4** [comment]
No response
