### ISSUE TITLE
[IMPROVEMENT] - Multiple Server Column Support

### ISSUE THREAD

**Issue by coniie** [NYRI4/LilyPichu#12]
**Describe the solution you'd like**
Support for use with mwittrien's Server Columns or built-in

**Describe alternatives you've considered**
mwittrien's Server Columns (incompatible)

**Comment by NYRI4** [comment]
Server Columns looks fine on my end

**Comment by coniie** [comment]
Sorry I meant the settings menu. It shows the first row of server columns so just scaling the settings menu to the number of columns. 
![image](https://user-images.githubusercontent.com/65280024/141735046-5a6d29fa-2bc9-4ced-b635-2bb8951b6a8a.png)

**Comment by NYRI4** [comment]
Not possible, the width/number of columns is set on the guild list, the setting container is way higher in the DOM
