### ISSUE TITLE
Theme Customization

### ISSUE THREAD

**Issue by kubaPL41567** [NYRI4/LilyPichu#14]
Hello, 

I really love this theme, but i wanted to ask, if you could make it so its fullscreen with no offset, if you can't do that, could you maybe tell me where i can edit it so I can do it myself? because i pretty much looked up the whole main.css and havent really found anything tbh.

Thank You!

**Comment by Ushie** [comment]
Can you check line 1837 and 1846? I noticed them when I was messing with the code and you should be able to do it by increasing the minimum px, if you want you can take the content of these two and put them in css snippets and increase the min px for them

**Comment by kubaPL41567** [comment]
> Can you check line 1837 and 1846? I noticed them when I was messing with the code and you should be able to do it by increasing the minimum px, if you want you can take the content of these two and put them in css snippets and increase the min px for them

ye, its doing something, but when its under 1920 it stays the same, and if above that, it just immediatelly jumps on the whole screen, and i wanted to keep the sidebar on the right

**Comment by Ushie** [comment]
Oh I misunderstood your question then, try removing the top and bottom elements on line 1849 and 1850? I'm not on my pc to check rn but that should be it

**Comment by kubaPL41567** [comment]
> Oh I misunderstood your question then, try removing the top and bottom elements on line 1849 and 1850? I'm not on my pc to check rn but that should be it the way I understood the question

Hey, yeah i just checked that, it works! Thank you!
Btw. do you maybe also know where i can make the member list bigger?

**Comment by Ushie** [comment]
I've actually attempted that and succeeded at only the member list, though search and threads were broken on that panel and i only managed to fix it partially, couldnt find everything and i had to give up, maybe Nyria can answer this for you when they're free

**Comment by kubaPL41567** [comment]
> I've actually attempted that and succeeded at only the member list, though search and threads were broken on that panel and i only managed to fix it partially, couldnt find everything and i had to give up, maybe Nyria can answer this for you when they're free

yeah, i have this for now ;P
![image](https://user-images.githubusercontent.com/95904802/145694029-fa6644d7-2dfb-47c3-98bd-5b8449a1d89f.png)

**Comment by AechSea** [comment]
> Oh I misunderstood your question then, try removing the top and bottom elements on line 1849 and 1850? I'm not on my pc to check rn but that should be it the way I understood the question

where can I find the lines, because the amount of lines for me is only until 62
