### ISSUE TITLE
This is just a request!

### ISSUE THREAD

**Issue by caikz** [NYRI4/LilyPichu#15]
Could you make this theme light mode and dark mode but without the LilyPichu type theme? I'm in love with how this looks and works but I'm not a big fan of the pink and bottom and top bit.. If you could I would really appreciate it!

**Comment by Ushie** [comment]
If it fits your interest, there's a community theme that uses the colors of Nyria's comfy theme on her LilyPichu theme, maybe it fits your need https://github.com/Ushie/Comfypichu

**Comment by caikz** [comment]
Thank you, but this is not what I was looking for. I was looking for a basic color scheme without all the pink, yellow and extra-ness. What I'm looking for is normal colors but the same layout and pop-outs.

**Comment by NYRI4** [comment]
no
