### ISSUE TITLE
Roles not showing

### ISSUE THREAD

**Issue by bananamilku** [NYRI4/LilyPichu#2]
Hi! I'm not really familiar with coding but for some reason when I click on someone the roles (+notes) don't show fully. It worked few days ago but suddenly it's not showing. Sorry if this a problem on my end but could you please take a look for me? That would be great :) Also I love your theme! (image included for reference) 
![스크린샷(65)](https://user-images.githubusercontent.com/84490926/118920553-7c780d80-b8eb-11eb-9624-c4c91a05d429.png)

**Comment by C13H10** [comment]
This could also be a discord problem and not a problem with the theme since i've been using the theme for a bit and haven't had a problem with this until today

**Comment by NeekoVN** [comment]
same here

**Comment by NeekoVN** [comment]
so betterdiscord just updated to v1.1.0, maybe that's why

**Comment by NYRI4** [comment]
Fixed (for now :PepeLaugh: banners inc)
