### ISSUE TITLE
Message @user clipping through user banner

### ISSUE THREAD

**Issue by Ventispurr** [NYRI4/LilyPichu#20]
![image](https://user-images.githubusercontent.com/91895035/149367987-20316b68-06fd-470f-9665-42c341ad7b2c.png)
 a fix for this is this 
 .footer-3naVBw {
margin-top: 20px;
padding: 0px;
}
:D

**Comment by NYRI4** [comment]
Did another, display: none KEKW

**Comment by Ventispurr** [comment]
good job llmaoo
