### ISSUE TITLE
member list/jump animation overlap

### ISSUE THREAD

**Issue by ItzRainbowMC** [NYRI4/LilyPichu#24]
![image](https://user-images.githubusercontent.com/103493212/171780734-27fbdb3c-5b03-475d-8e5f-9dffde9b9ea8.png)
 
tried asking help in theme-support and tried restarting discord and reinstalling BD but nothing worked

**Comment by ItzRainbowMC** [comment]
sorry i i hadnt blurred the users but I did the screenshot in comfy camp

**Comment by NYRI4** [comment]
Guess this is fixed ?
