### ISSUE TITLE
sidebar is a little jank and the font doesn't work

### ISSUE THREAD

**Issue by N3xusSt4r** [NYRI4/LilyPichu#25]
![Screenshot 2023-02-07 192637](https://user-images.githubusercontent.com/124746206/217397989-6766ad40-9328-4ed9-972c-becfe575cb6e.png)
i'm using betterdiscord and there are a couple issues. the font doesn't work (in titles, forgot to say that), and assets of the sidebar are missing. overall, it's nice, but there are just a few tidbits that are nagging me.

**Comment by NYRI4** [comment]
@N3xusSt4r Still an issue ?
