### ISSUE TITLE
Idk what to title this.

### ISSUE THREAD

**Issue by Iplay4u** [NYRI4/LilyPichu#29]
I don't know how to surmise the issue in a few short words, but here's the long and short of it. With certain addons (in my case BetterFolders on Vencord) when a sidebar appears pushing the main text window away, it forces the text window as far as it will go rather than by the specified amount. I had to compress the video with a bad online compressor so I'm sorry about the lossy quality.

https://user-images.githubusercontent.com/84083925/229894232-073ff3e1-8ae4-4cb0-b519-65f982064388.mp4

**Comment by NYRI4** [comment]
I don't have the motivation nor time to support all plugins of BetterDiscord, Replugged, Vencord, Shelter ... on 3 different themes, while Discord is rolling updates every months breaking them at one point, if you really want BetterFolders support, learn HTML/CSS it's fun and you can make some funny shit with it.
