### ISSUE TITLE
Can we change the yellow/gold color on the left side?

### ISSUE THREAD

**Issue by Dernasur** [NYRI4/LilyPichu#31]
As the title says, I don't really know where to look to change the color of the yellow/gold in the background. 

With the colors I want to go with, the yellow/gold is very conflicting.

If there is somewhere in the code to do so, any help to locate it would be appreciated!

![image](https://github.com/NYRI4/LilyPichu/assets/19523054/b3f5f8b2-c576-437f-926e-688e821af5a7)
![image](https://github.com/NYRI4/LilyPichu/assets/19523054/a9e5c056-dec9-4c74-a679-01f6c8165aa1)

**Comment by NYRI4** [comment]
It's not customisable because it's pictures, eventually you can open Photoshop, recolor those, host those images and replace the url here : 

```css
:root .app-3xd6d0::before {
    background: url('https://i.imgur.com/jTpFJuI.png') no-repeat;
}
:root .app-3xd6d0::after {
    background: url('https://i.imgur.com/KQQWcTY.png') no-repeat;
}
