### ISSUE TITLE
The selection hover is not showing

### ISSUE THREAD

**Issue by Crepper99** [NYRI4/LilyPichu#32]
Hey, when I mention someone or pick an emoji from the chat, I can't see the hover "effect" indicating which user/emoji I have chosen.

Have the latest version installed and using vencord custom CSS editor.
![image](https://github.com/NYRI4/LilyPichu/assets/84658142/dcdce76d-3137-47e8-853c-c6bad514da32)
![image](https://github.com/NYRI4/LilyPichu/assets/84658142/30d0b4c3-8d03-4b0e-b3f1-1eb33e6c24c1)

**Comment by NYRI4** [comment]
Weird that I didn't noticed that at all 🤔

**Comment by Crepper99** [comment]
So is there some fast fix?

**Comment by Crepper99** [comment]
fixed :)
