### ISSUE TITLE
Nitro profile picture decorations not centered in message search

### ISSUE THREAD

**Issue by myang7** [NYRI4/LilyPichu#33]
When I use the search feature with this theme enabled, the avatar decorations in the sidebar go off to the side, whereas usually in the member list, this does not happen.
![2023-06-04-121453_61x59_scrot](https://github.com/NYRI4/LilyPichu/assets/65783258/b37985b4-3ec1-4b9e-8be9-3f485ae299ec)
It'll end up looking something like this

**Comment by NYRI4** [comment]
Guess that issue is useless since picture decorations are not anymore
