### ISSUE TITLE
Nitro profile backgrounds are trimmed.

### ISSUE THREAD

**Issue by makmakkmak** [NYRI4/LilyPichu#36]
![image](https://github.com/NYRI4/LilyPichu/assets/123666593/5e502cdf-9eb8-4dfc-90af-1b216dcce7a6)
The LilyPichu theme is really nice but this issue is really annoying me how when people have images are their banner, it gets cropped.

**Comment by NYRI4** [comment]
It is to create a nice gradient looking banner, if you wanna see the full banner click on the username of the user you're looking
