### ISSUE TITLE
Checkbox isn't checkboxing (Visual)

### ISSUE THREAD

**Issue by Crepper99** [NYRI4/LilyPichu#37]
When you check a box it doesn't show any difference from the checked or not checked box. It's annoying in "Browse Channels" cuz you can't see which is checked. I will send screenshots.
![image](https://github.com/NYRI4/LilyPichu/assets/84658142/6d1def65-2f6a-4ea2-8b6a-dd4467daf6d3) = Checked
![image](https://github.com/NYRI4/LilyPichu/assets/84658142/10ffe844-9925-4d71-b0f5-0bd8de789bf6) = Unchecked

**Comment by Sergio-Bianchi** [comment]
There is the same problem with the checkbox for trusted links
