### ISSUE TITLE
User Profile isn't where it's supposed to be.

### ISSUE THREAD

**Issue by nVixor** [NYRI4/LilyPichu#38]
This started with the recent discord update that broke a bunch of addons on replugged as well.
I wish I could be of more use but sadly, I don't know CSS *at all*

![image](https://github.com/NYRI4/LilyPichu/assets/49826107/6db3defa-a355-48d3-8850-aae37f2822e4)

**Comment by destellr** [comment]
Made a profile just to comment on this! I desperately want to fix this :( If anyone knows how to fix it please let me and op know
