### ISSUE TITLE
User Member List Issue

### ISSUE THREAD

**Issue by SketchAsylum** [NYRI4/LilyPichu#39]
I do not know if it's just a better discord issue, but the member list is now on the side of the chatbox rather than within the container made for the theme. It was fine yesterday, but when I opened Discord - it appeared like this; I even tried repairing Better Discord to see if that was the issue.

**Comment by therealolie** [comment]
can confirm, both member list and dm-profile thingie are broken
![image](https://github.com/NYRI4/LilyPichu/assets/46534106/e9fad768-4bad-4e0b-87f5-1dfa16a9d030)
![image](https://github.com/NYRI4/LilyPichu/assets/46534106/fec8ee4f-cb35-44de-b812-574903d91986)
