### ISSUE TITLE
"Stay Comfy" gif

### ISSUE THREAD

**Issue by rwbrry** [NYRI4/LilyPichu#4]
Is is possible to make the gif of Lilypichu jumping up and down customizable? It moves too fast and quite distracting while I use my normal dms

**Comment by hoyupu** [comment]
If you're in the Discord, a CSS snippet has just been pushed for this, adding that to your Custom CSS will fix this

**Comment by rwbrry** [comment]
> If you're in the Discord, a CSS snippet has just been pushed for this, adding that to your Custom CSS will fix this

The discord link connected to the creator's acc is currently invalid! Or it expired! If you can send me a new disc inv id be grateful! thank you

**Comment by hoyupu** [comment]
of course! here you go!!

https://discord.gg/MMTVuTP8

**Comment by rwbrry** [comment]
thank you so much <3
