### ISSUE TITLE
The theme isn't wotking

### ISSUE THREAD

**Issue by Shep0712** [NYRI4/LilyPichu#44]
lilypichu theme isn't working right for me, first the member list is bugging then the server folder is bugging and now it doesn't even have the box on the right at all

**Comment by Shep0712** [comment]
![Screenshot (704)](https://github.com/NYRI4/LilyPichu/assets/148936324/38e59bd9-8068-4286-b5a1-f68f7a831a03)

**Comment by FlareGod** [comment]
same issue for me, discord recently updated so themes and plugins have to be manually updated - should be fixed within a couple days
