### ISSUE TITLE
profile on right side not scaled properly to the box 

### ISSUE THREAD

**Issue by raffieal** [NYRI4/LilyPichu#49]
<img width="401" alt="Screenshot 2024-02-14 at 10 32 14" src="https://github.com/NYRI4/LilyPichu/assets/157590745/1514ab9d-17c8-497f-91c3-bd2a41796ec5">

**Comment by PinkSerenity** [comment]
I made a temporary fix. I will delete it as soon as the pull request gets merged. Use this URL:
https://[raw.githubusercontent.com/PinkSerenity/LilyPichu/temp/lilypichu.theme.css](https://raw.githubusercontent.com/PinkSerenity/LilyPichu/temp/lilypichu.theme.css)

**Comment by therealolie** [comment]
fixed!

**Comment by PinkSerenity** [comment]
Yay, thank you :3
