### ISSUE TITLE
member list box gone

### ISSUE THREAD

**Issue by aquaakya** [NYRI4/LilyPichu#51]
the member list and stuff is in its default discord location instead of the box on the side.
![image](https://github.com/NYRI4/LilyPichu/assets/165261649/aefc154f-6c1f-455a-9802-1c151e5871f7)

**Comment by Thedigchanelh1** [comment]
yeah even happening for me 
![Screenshot 2024-03-28 150929](https://github.com/NYRI4/LilyPichu/assets/84262536/09db819a-fdda-4ebe-a85e-cabfe980ffc4)
![Screenshot 2024-03-28 150900](https://github.com/NYRI4/LilyPichu/assets/84262536/b41823a4-8a73-4e0f-ae07-486b52ed184f)

**Comment by therealolie** [comment]
fixed in #52, we just need to wait for nyria to wake up
