### ISSUE TITLE
Profile pop-up issues after recent update

### ISSUE THREAD

**Issue by thegreenvalley** [NYRI4/LilyPichu#6]
Since discord has added a new "about me" section it dramatically increased the width of the usercard page, and also created this strange effect that goes into the user's roles. 
![2021-06-24 15_34_46-memes - Discord_LI](https://user-images.githubusercontent.com/35157673/123329289-463d3780-d502-11eb-9a2c-4aeb20bf06da.jpg)

**Comment by tessmam** [comment]
the same thing is happening to me, not sure how to fix it ;;
